Updated scripts in tools

diff --git a/tools/art_from_images b/tools/art_from_images
--- a/tools/art_from_images
+++ b/tools/art_from_images
@@ -1,163 +1,256 @@
 #!/usr/bin/env bash
 
-clean() { rm -f $script; exit 0; }
+### Helpers begin
+set -o noglob
+trap "clean 128" SIGINT # Ensure cleanup on ^C
+check_deps() {
+    for d in "${deps[@]}"; do
+        [[ -n $(command -v "$d") ]] || errx 127 "$d is not installed"
+    done; unset d
+}
+check_lock() {
+    [[ -n $cache ]] || errx 126 "Cache is not defined"
+    mkdir -p "$cache"
+    if [[ -f "$cache.lock" ]]; then
+        errx 125 "$cache.lock already exists"
+    fi
+    echo "$$" >"$cache.lock"
+}
+check_resume_file() {
+    if [[ -f "$json" ]] && [[ -z $resume ]]; then
+        warn "Resume file found" >&2
+        while :; do
+            # Prompt whether to overwrite or resume
+            local a
+            read -n 1 -p "Would you like to resume [y/n/q/c]: " -rs a
+            echo
 
-err() { echo -e "${clr:+\e[31m}[!] ${@:2}\e[0m"; exit $1; }
-
-info() { echo -e "${clr:+\e[37m}[=] $@\e[0m"; }
-
+            case "$a" in
+                "c") clean 0 ;;
+                "n") write_resume_file; break ;;
+                "q") exit 0 ;;
+                "y") read_resume_file; resume="--resume"; break ;;
+                *) echo "Invalid response, try again!" ;;
+            esac
+        done
+    elif [[ -f "$json" ]]; then
+        read_resume_file
+    elif [[ -n $resume ]]; then
+        errx 124 "No resume file found"
+    else
+        write_resume_file
+    fi
+}
+clean() {
+    if [[ ${1:-0} -eq 0 ]]; then
+        [[ -z $cache ]] || [[ ! -d "$cache" ]] || rm -rf "$cache"
+    fi
+    [[ -z $script ]] || [[ ! -f "$script" ]] || rm -f "$script"
+    [[ ${1:-0} -eq 125 ]] || [[ -z $cache ]] || rm -f "$cache.lock"
+    show_cursor
+    exit "${1:-0}"
+}
+err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
+errx() { echo -e "${color:+\e[31m}[!] ${*:2}\e[0m"; clean "$1"; }
+good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
+hide_cursor() { echo -en "\e[?25l"; }
+info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
+json_get() {
+    if [[ -z $json ]] || [[ ! -f "$json" ]]; then
+        return
+    fi
+    jq -cr ".$*" "$json" | sed -r "s/^null$//g"
+}
 long_opt() {
     local arg shift="0"
     case "$1" in
-        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 1 ;;
-        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 1; arg="$1" ;;
+        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 123 ;;
+        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 123; arg="$1" ;;
     esac
     echo "$arg"
     return $shift
 }
+show_cursor() { echo -en "\e[?25h"; }
+subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
+warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
+### Helpers end
 
-usage() {
-    echo "Usage: ${0/*\//} [OPTIONS]"
-    echo
-    echo "Parse images and create ruby code for ArTTY"
-    echo
-    echo "Options:"
-    echo "    -f, --force          Create ruby code even if it exists"
-    echo "    -h, --help           Display this help message"
-    echo "    -i, --imgs=DIR       Read images from the specified"
-    echo "                         directory, can be used more than"
-    echo "                         once (default: $dir)"
-    echo "    --nocolor            Don't colorize output"
-    echo "    -o, --output=DIR     Write files to specified directory"
-    echo "                        (default: $output)"
-    echo "    -p, --parallel       Run using parallel (if installed)"
-    local default="(default: $threads)"
-    echo "    -t, --threads=NUM    Use the specied number of threads"
-    echo "                         if running in parallel $default"
-    echo
-    exit $1
+read_resume_file() {
+    force="$(json_get "force")"
+    while read -r dir; do
+        dirs+=("$dir")
+    done < <(json_get "imgs[]"); unset dir
+    output="$(json_get "output")"
 }
 
-warn() { echo -e "${clr:+\e[33m}[-] $@\e[0m"; }
+usage() {
+    cat <<EOF
+Usage: ${0##*/} [OPTIONS]
 
-declare -a args dirs
-unset force help parallel
-clr="true"
-dir="."
+Parse images and create ruby code for ArTTY.
+
+Options:
+    -f, --force          Create ruby code even if it exists
+    -h, --help           Display this help message
+    -i, --imgs=DIR       Read images from the specified directory, can
+                         be used more than once (default: .)
+    --nocolor            Disable colorized output
+    -o, --output=DIR     Write files to specified directory (default:
+                         .)
+    -r, --resume         Resume from a previous run
+    -t, --threads=NUM    Use specified number of threads (default: 32)
+    -v, --verbose        Do not hide parallel errors
+
+EOF
+    exit "$1"
+}
+
+write_resume_file() {
+    [[ -n $cache ]] || return
+    [[ -n $json ]] || return
+    rm -rf "$cache"
+    mkdir -p "$cache"
+
+    cat >"$json" <<EOF
+{
+  "force": "$force",
+  "imgs": [
+$(
+    for i in $(seq 1 ${#dirs[@]}); do
+        echo "    \"${dirs[$i - 1]}\"${dirs[$i]:+,}"
+    done; unset i
+)
+  ],
+  "output": "$output"
+}
+EOF
+}
+
+declare -a args deps dirs
+unset force help
+color="true"
+deps+=("arTTY")
+deps+=("jq")
 output="."
+parallel="true"
 threads="32"
 
+# Check for missing dependencies
+check_deps
+
+# Parse command line options
 while [[ $# -gt 0 ]]; do
     case "$1" in
         "--") shift && args+=("$@") && break ;;
         "-f"|"--force") force="true" ;;
         "-h"|"--help") help="true" ;;
-        "-i"|"--imgs"*) dirs+=($(long_opt $@)) || shift ;;
-        "--nocolor") unset clr ;;
-        "-o"|"--output"*) output="$(long_opt $@)" || shift ;;
-        "-p"|"--parallel") parallel="true" ;;
-        "-t"|"--thread"*) threads="$(long_opt $@)" || shift ;;
+        "-i"|"--imgs"*) dirs+=("$(long_opt "$@")") || shift ;;
+        "--nocolor") unset color ;;
+        "-o"|"--output"*) output="$(long_opt "$@")" || shift ;;
+        "-r"|"--resume") resume="--resume" ;;
+        "-t"|"--threads"*) threads="$(long_opt "$@")" || shift ;;
+        "-v"|"--verbose") verbose="true" ;;
         *) args+=("$1") ;;
     esac
     shift
 done
-[[ -z ${args[@]} ]] || set -- "${args[@]}"
+[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"
 
-# Check for valid params and missing dependencies
+# Check for valid params
 [[ -z $help ]] || usage 0
-[[ $# -eq 0 ]] || usage 2
+[[ $# -eq 0 ]] || [[ -n $resume ]] || usage 1
 
 # Determine parallel situation
 if [[ -n $parallel ]] && [[ -z $(command -v parallel) ]]; then
-    warn "Parallel is not installed, using default behavior"
+    warn "Parallel is not installed, defaulting to single-threaded"
     unset parallel
 fi
 
 # Cite if needed
-if [[ -n $parallel ]] && [[ ! -f $HOME/.parallel/will-cite ]]; then
-    mkdir -p $HOME/.parallel
+if [[ -n $parallel ]] && [[ ! -f "$HOME/.parallel/will-cite" ]]; then
+    mkdir -p "$HOME/.parallel"
     parallel --citation
 fi
 
-# Script used by parallel
-script="/tmp/${0/*\//}.parallel"
-trap clean SIGINT
+# Cache variables
+hash="$(pwd | sha256sum | awk '{print $1}')"
+cache="$HOME/.cache/${0##*/}/$hash"
+joblog="$cache/joblog.txt"
+json="$cache/${0##*/}.json"
 
-cat >$script <<EOF
-#!/usr/bin/env bash
+# Lock to prevent parallel issues
+check_lock
 
-err() { echo -e "\r${clr:+\e[31m}[!] \${@:2}\e[0m\e[K"; exit \$1; }
+# Check for resume file
+[[ -z $parallel ]] || check_resume_file
+hide_cursor
 
-# info() { echo -e "\r${clr:+\e[32m}[+] \$@\e[0m\e[K"; }
-
-# warn() { echo -e "\r${clr:+\e[33m}[-] \$@\e[0m\e[K"; }
-
-filename="\$1"
-ofilename="\$(
-    echo "\${filename%_*}" | awk -F "/" '{print \$NF}' | \\
-    sed -r "s/[-.]/_/g" | tr "[:upper:]" "[:lower:]"
-).rb"
-
-[[ ! -f $output/\$ofilename ]] || [[ "x$force" != "x" ]] || exit 1
-
-arTTY -g \$filename >$output/\$ofilename
-
-if [[ -n \$(find $output/\$ofilename -size 0) ]]; then
-    err 1 "\$filename failed"
-fi
-EOF
-chmod 700 $script
-
-[[ ${#dirs[@]} -gt 0 ]] || dirs=($dir)
-mkdir -p $output
+[[ -z $resume ]] || info "Resuming..."
 
 info "Processing dataset for jobs"
 
-declare -a dataset=($(
-    find ${dirs[@]} -mindepth 1 -maxdepth 1 -regextype awk \
-    -iregex ".+_[0-9]+x[0-9]+\.(jpg|png)"
-))
-let "total = ${#dataset[@]}"
+dataset="$cache/${0##*/}.dataset"
+if [[ ! -f "$dataset" ]]; then
+    [[ ${#dirs[@]} -gt 0 ]] || dirs=(".")
+    for dir in "${dirs[@]}"; do
+        find "$dir" -mindepth 1 -maxdepth 1 -regextype awk \
+            -iregex ".+_[0-9]+x[0-9]+\.(jpg|png)" >>"$dataset"
+    done; unset dir
+fi
+total="$(wc -l "$dataset" | awk '{print $1}')"
+[[ $total -gt 0 ]] || errx 2 "No dataset provided"
 
-[[ $total -ne 0 ]] || err 3 "No dataset provided"
+subinfo "$total jobs to run"
 
-info "$total jobs to run"
+# Create sub-script
+script="/tmp/${0##*/}.parallel"
+cat >"$script" <<EOF
+#!/usr/bin/env bash
+
+### Helpers begin
+set -o noglob
+err() { echo -e "\r${color:+\e[31m}[!] \$*\e[0m\e[K"; }
+errx() {
+    echo -e "\r${color:+\e[31m}[!] \${*:2}\e[0m\e[K"
+    exit "\$1"
+}
+good() { echo -e "\r${color:+\e[32m}[+] \$*\e[0m\e[K"; }
+info() { echo -e "\r${color:+\e[37m}[*] \$*\e[0m\e[K"; }
+subinfo() { echo -e "\r${color:+\e[36m}[=] \$*\e[0m\e[K"; }
+warn() { echo -e "\r${color:+\e[33m}[-] \$*\e[0m\e[K"; }
+### Helpers end
+
+filename="\$1"
+ofilename="\$(
+    echo "\${filename%_*}" | awk -F "/" '{print \$NF}' | \
+    sed -r "s/[-.]/_/g" | tr "[:upper:]" "[:lower:]"
+).rb"
+
+[[ ! -f "$output/\$ofilename" ]] || [[ "x$force" != "x" ]] || exit 1
+
+arTTY -g \$filename >"$output/\$ofilename"
+
+if [[ -n \$(find "$output/\$ofilename" -size 0) ]]; then
+    errx 1 "\$filename failed"
+fi
+EOF
+chmod 700 "$script"
+
+mkdir -p "$output"
+
+# Run sub-script
 if [[ -n $parallel ]]; then
-    # Math
-    left="$total"
-    marker="0"
-    maxdata="$(
-        parallel -r --show-limit </dev/null | \
-        awk '/Maximal used/ {print $NF; exit}'
-    )"
-    let "remainder = total % maxdata"
-    round="0"
-    let "rounds = total / maxdata"
-    [[ $remainder -eq 0 ]] || let "rounds += 1"
-
-    # Loop thru rounds
-    [[ $rounds -eq 1 ]] || info "Splitting into $rounds rounds"
-    while [[ $left -gt 0 ]]; do
-        let "round += 1"
-        [[ $rounds -eq 1 ]] || warn "Round $round"
-
-        increment="$left"
-        [[ $left -le $maxdata ]] || increment="$maxdata"
-
-        parallel --bar --lb -P $threads -r $script {} ::: \
-            ${dataset[@]:$marker:$increment}
-
-        let "left -= increment"
-        let "marker += increment"
-        echo -en "\e[1A\e[K"
-    done
+    parallel -a "$dataset" --bar --joblog ${resume:++}"$joblog" --lb \
+        -P "$threads" -r $resume "$script" {}
+    [[ -n $verbose ]] || echo -en "\e[1A\e[K" >&2
 else
-    let "count = 1"
-    for data in "${dataset[@]}"; do
-        echo -en "\r[$count/$total]\e[K" >&2
+    count="1"
+    while read -r data; do
+        echo -e "\r\e[K" >&2
+        echo -en "${color:+\e[37m}[$count/$total]\e[0m\e[K\e[1A" >&2
         $script "$data"
-        let "count += 1"
-    done; unset data
+        ((count += 1))
+    done <"$dataset"; unset data
 fi
 
 clean
